# Generated by Django 6.0.2 on 2026-09-21 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotpverifications',
            name='error_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
